### ISSUE TITLE
Sync on startup

### ISSUE THREAD

**Issue by pclemins** [Vermont-EPSCoR/Macroinvertebrates#11]

**Comment by MorganRodgers** [comment]
Branch autosynconce is an attempt at making a user friendly version of this. Have you had a chance to look at its most recent commits?

**Comment by pclemins** [comment]
All right... this looks good and my changes are now in autosynconce.

You check them out and if you like them, submit a pull request to merge autosynconce into master and I'll delete this branch and call it a day.

**Comment by pclemins** [comment]
No autosync, but prompts user to sync if there's no bug data in the app at startup.
