### ISSUE TITLE
Have UI update during sync process

### ISSUE THREAD

**Issue by pclemins** [Vermont-EPSCoR/Macroinvertebrates#13]

**Comment by MorganRodgers** [comment]
Complete?

**Comment by pclemins** [comment]
Nope... Was at the statehouse today.  Do you want to play around with
this?  Are all the other V2 tasks done?

Pat

**Comment by MorganRodgers** [comment]
Of the priority V2 tasks, the placeholder task could use more work.

**Comment by pclemins** [comment]
Completed using dispatch_async blocks.  Branch UIUpdating completes this work.
