### ISSUE TITLE
Check for new photo based on time stamp, not photo name as is done currently

### ISSUE THREAD

**Issue by pclemins** [Vermont-EPSCoR/Macroinvertebrates#14]

**Comment by MorganRodgers** [comment]
Using a HEAD HTTP request we can get a file's Last-Modified date. A better option would be using the [ETag](https://en.wikipedia.org/wiki/HTTP_ETag) which is effectively a checksum for the file. While ETag is an optional feature for webservers it is supported by both Apache and Nginx instances used by Wikieducator and UVM's webfiles respectively.

**Comment by pclemins** [comment]
Almost done:

We can get the timestamp easy with the API at the same time we get the thumbnail URLs in 
getBugImageURLsWeb in WebData.m.

We need to modify the URL a tad:

http://wikieducator.org/api.php?action=query&iiurlwidth=400&prop=imageinfo&iiprop=url|timestamp&format=json&titles=%@

i.e.

http://wikieducator.org/api.php?action=query&iiurlwidth=400&prop=imageinfo&iiprop=url|timestamp&format=json&titles=File:Chironomidae.jpg

and then adjust the parsing slightly to get the timestamp as well.

Then, there’s a few option on where to do the timestamp check… 1) return a more complicated Dictionary which contains a URL and a timestamp and then compare during the background image download, 2) only add the Filename and URL to the Dictionary if the timestamp is newer than the one already stored, 3) something else?

**Comment by pclemins** [comment]
Oh, and here's the page for the ImageInfo API:

https://www.mediawiki.org/wiki/API:Imageinfo

**Comment by pclemins** [comment]
And yet one more thing... we can also use the sha1 hash to compare images... I'm file with that OR timestamp...

**Comment by MorganRodgers** [comment]
Check pull request #23.

**Comment by MorganRodgers** [comment]
I think this is ready to close. Agreed?

**Comment by pclemins** [comment]
Yes!  Looks like it worked great!

Let's close out the timestamp branch as well... a pull request will get me
to do that and then I'll delete the timestamp branch as well.

Pat

**Comment by MorganRodgers** [comment]
Pull request closed.
