### ISSUE TITLE
WikiStyle Links Cluttering Invertebrate Descriptions

### ISSUE THREAD

**Issue by MorganRodgers** [Vermont-EPSCoR/Macroinvertebrates#24]
A number of invertebrate descriptions there are Wiki formatted links to images, or perhaps other articles. While these links are great for users of the webpage they are not handled properly in this application, and ought to be removed or reformatted.

Text descriptions may be extracted using the regular expression: ```"\[http[^ ]+ ([^]]+)\]"```.

**Comment by pclemins** [comment]
Yeah... noticed this.  Definitely tackle this if you want...

Pat

**Comment by MorganRodgers** [comment]
Commit 75f2987532d9503ea7af4b9d359b6d167e3ec946 in MorganRodgers/MacroinvertebratesV3 handles this issue. We can leave it be in V2, or I can back port?

**Comment by pclemins** [comment]
You could definitely back port, but the other things on that list of issues
is higher priority...

Pat

**Comment by MorganRodgers** [comment]
Pull request closed.
