### ISSUE TITLE
Add Exit Button to Main Screen

### ISSUE THREAD

**Issue by pclemins** [Vermont-EPSCoR/Macroinvertebrates#5]

**Comment by MorganRodgers** [comment]
I just poked around Stack a bit and found that the preferred way to exit an iOS application is for the user to hit the home button.

From the horse's mouth:
> Q:  How do I programmatically quit my iOS application?
> 
> A: There is no API provided for gracefully terminating an iOS application.
https://developer.apple.com/library/ios/qa/qa1561/_index.html

**Comment by pclemins** [comment]
I figured as much... So... we should purge the app of any exit() calls...

Pat

**Comment by pclemins** [comment]
exit() calls purged
