### ISSUE TITLE
Streams don't list on sync screen

### ISSUE THREAD

**Issue by pclemins** [Vermont-EPSCoR/Macroinvertebrates#6]
Happened once... reproduce?

**Comment by MorganRodgers** [comment]
Did you have a network outage, or the server was hiccuping? I toggled back to the sync page once after syncing and it took a moment for the streams to list again. I'd assume that this is ultimately a network issue.

**Comment by pclemins** [comment]
Yeah... so the stream pull is asynchronous... I noticed that the other
day.  The server was probably just a bit slow.  If you want to put up a
"Downloading Streams" notice and drop it when the streams are done, feel
free...

Pat

**Comment by MorganRodgers** [comment]
5a59211 causes the modal which tells users that syncing everything will take ~20 seconds to pop immediately. I'm hesitant to add more flicker to this view: we are already showing three modal pop ups:

- 20 second notification
- Streams are downloading
- Streams complete/images starting notification

Solved?

**Comment by pclemins** [comment]
Great idea!  This seems like a good fix...
